export const dummyPosts = [
  {
    postId: 'O7IK46V9RYX7M5S',
    uid: 'iiu1q4b3t34sc4l0fnr',
    timestamp: '07/06/2022',
    name: 'Yoko',
    username: 'ywinston0',
    content:
      'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',
    likes: 904,
  },
  {
    postId: 'AEC7UUHIA4KM6P9',
    uid: '2acpykwm38rmnu5uo4i',
    timestamp: '05/10/2022',
    name: 'Elka',
    username: 'ecostan1',
    content:
      'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',
    likes: 2387,
  },
  {
    postId: 'VMDQ7RYWTNZPBWC',
    uid: 'tv3ujrnp0ewsc14yjfc',
    timestamp: '06/17/2022',
    name: 'Sherye',
    username: 'sespinazo2',
    content:
      'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
    likes: 6744,
  },
  {
    postId: 'O1HU7BULZNRV2Y7',
    uid: 'dadwdp5qxjusxs2mln9',
    timestamp: '05/03/2022',
    name: 'Mollie',
    username: 'mhullock3',
    content:
      'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',
    likes: 5394,
  },
  {
    postId: 'DL9RSTYMY695D03',
    uid: '6zzmlux4hcs6tw0qmmf',
    timestamp: '10/10/2022',
    name: 'Lind',
    username: 'lfurneaux4',
    content:
      'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.',
    likes: 1378,
  },
  {
    postId: 'Q9RMXO5629EAMI8',
    uid: 'ze8ly9k0cih426w2qrm',
    timestamp: '01/07/2022',
    name: 'Justina',
    username: 'jjoddins5',
    content:
      'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.',
    likes: 1501,
  },
  {
    postId: 'KIFY9U5M9H56M2B',
    uid: 'ey8asmcqte2bwyavdc6',
    timestamp: '01/08/2022',
    name: 'Clari',
    username: 'celton6',
    content: 'In congue. Etiam justo. Etiam pretium iaculis justo.',
    likes: 7165,
  },
  {
    postId: 'KKKD3WTXHL9V2FH',
    uid: '2dlsdomq13agvt80vzf',
    timestamp: '07/18/2022',
    name: 'Lyndy',
    username: 'lchurchouse7',
    content: 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
    likes: 9678,
  },
  {
    postId: 'SW74FV1YMB2BA4N',
    uid: 'vq3flyca78dx3tvjnp9',
    timestamp: '06/22/2022',
    name: 'Lindie',
    username: 'lmartinon8',
    content:
      'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
    likes: 8928,
  },
  {
    postId: 'M42Q30HPS6I7GPJ',
    uid: '4web4cl431ntxi5mfat',
    timestamp: '04/09/2022',
    name: 'Ham',
    username: 'htoffoloni9',
    content:
      'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',
    likes: 7215,
  },
  {
    postId: 'Y2IVAY49QJ03SPV',
    uid: '9cbrjybyx7khg6dd3mb',
    timestamp: '02/16/2022',
    name: 'Ciel',
    username: 'ceteena',
    content:
      'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.',
    likes: 3749,
  },
  {
    postId: 'TX5CKO008FTYW1B',
    uid: 'vekq64sen6uxgg1p3qk',
    timestamp: '09/08/2022',
    name: 'Inesita',
    username: 'ielvenb',
    content:
      'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.',
    likes: 9994,
  },
  {
    postId: 'YBUHQK7AXNIKVXA',
    uid: '4z3gmyu262yn2jl45w2',
    timestamp: '08/13/2022',
    name: 'Fax',
    username: 'fminterc',
    content:
      'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
    likes: 4115,
  },
  {
    postId: '46EDEWJN0D5ZV04',
    uid: '3krg7ogb5s7dlzfkocg',
    timestamp: '04/03/2022',
    name: 'Deeann',
    username: 'dmacairtd',
    content:
      'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',
    likes: 8032,
  },
  {
    postId: '5DMSFCUJ4V27XWE',
    uid: 'b6gygks2owra5kr2z9r',
    timestamp: '10/09/2022',
    name: 'Zorine',
    username: 'zforstere',
    content:
      'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
    likes: 3219,
  },
  {
    postId: '57AW0C9KXKKTZ0L',
    uid: '95ccd2pyhz73kty0e0r',
    timestamp: '03/29/2022',
    name: 'Natalina',
    username: 'nhobbemaf',
    content:
      'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
    likes: 1958,
  },
  {
    postId: 'MWDQVOB498FHWUV',
    uid: 'rxdkf0lpnb2n6tk9gla',
    timestamp: '08/03/2022',
    name: 'Gibby',
    username: 'gheritegeg',
    content: 'Sed ante. Vivamus tortor. Duis mattis egestas metus.',
    likes: 5463,
  },
  {
    postId: 'DKSBLX10BZ5CPT5',
    uid: 'mkteog4podden5aulvg',
    timestamp: '12/22/2022',
    name: 'Bengt',
    username: 'branklinh',
    content:
      'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
    likes: 5151,
  },
  {
    postId: 'PZ8DHWQ29RS0YS7',
    uid: '6o0wrza4p8bcm8xxny6',
    timestamp: '06/01/2022',
    name: 'Maximilien',
    username: 'mfalli',
    content:
      'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.',
    likes: 8937,
  },
  {
    postId: 'VJQLTQI0PBRN1JP',
    uid: '05sqdvso25ry39bjyd4',
    timestamp: '05/21/2022',
    name: 'Alidia',
    username: 'aforgiej',
    content: 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.',
    likes: 7239,
  },
  {
    postId: 'AO1HZ3VGJ0WH2DH',
    uid: 'bedmkdtox2nayngcif8',
    timestamp: '05/01/2022',
    name: 'Hanson',
    username: 'hbrocktonk',
    content:
      'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
    likes: 8316,
  },
  {
    postId: '6070V9TAH14XBZ3',
    uid: 'qdjubepaeej9udtvkcv',
    timestamp: '05/02/2022',
    name: 'Ryun',
    username: 'rdehavenl',
    content:
      'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
    likes: 6694,
  },
  {
    postId: 'CMJ5WJCJUWGPD2U',
    uid: 'm3654xcyeu0w0h8d7tr',
    timestamp: '02/15/2022',
    name: 'Edithe',
    username: 'ehumpatchm',
    content:
      'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',
    likes: 4582,
  },
  {
    postId: 'JOFQUJ1L04T5MKH',
    uid: 'rmp8z3yac65mwg5exsd',
    timestamp: '03/27/2022',
    name: 'Washington',
    username: 'wjarmainen',
    content:
      'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
    likes: 2198,
  },
  {
    postId: '3KBI5KNWHF4KJ1P',
    uid: '15nj6y8aky4kaqhc3od',
    timestamp: '10/11/2022',
    name: 'Tove',
    username: 'twearno',
    content:
      'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
    likes: 2704,
  },
  {
    postId: 'TWOMH330JAM0FOU',
    uid: 'y6fom21nab7aphdb4cw',
    timestamp: '01/07/2022',
    name: 'Had',
    username: 'hmastrantonep',
    content:
      'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',
    likes: 3939,
  },
  {
    postId: '8317G0IDE2N6A27',
    uid: 'jysj2m9b8wxhvrokpzk',
    timestamp: '04/06/2022',
    name: 'Daisey',
    username: 'dfaldoeq',
    content: 'Fusce consequat. Nulla nisl. Nunc nisl.',
    likes: 6585,
  },
  {
    postId: 'OSU6TR6DQHX5FWV',
    uid: '70jr26sr47pd26mqxgg',
    timestamp: '02/09/2022',
    name: 'Irina',
    username: 'ichatelotr',
    content:
      'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',
    likes: 314,
  },
  {
    postId: 'SY3IDS9FIZFWPFV',
    uid: 'ku2q0y37lzm83uup4xm',
    timestamp: '12/13/2022',
    name: 'Mill',
    username: 'mbaskeyfieds',
    content:
      'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',
    likes: 4394,
  },
  {
    postId: 'DV7CEHM9QPF148H',
    uid: 'mvlo7os1ls7gx0d0up1',
    timestamp: '02/16/2022',
    name: 'Meade',
    username: 'mreant',
    content: 'Sed ante. Vivamus tortor. Duis mattis egestas metus.',
    likes: 1603,
  },
  {
    postId: 'RTH3UBBOVZHO0EY',
    uid: 'uz09gr2yr35x2g74bxm',
    timestamp: '04/21/2022',
    name: 'Dori',
    username: 'dsappellu',
    content:
      'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    likes: 2361,
  },
  {
    postId: 'HOLKIYO7ZA2GR5T',
    uid: '0xv8n55utrceomfyaei',
    timestamp: '02/19/2022',
    name: 'Tymothy',
    username: 'twasielv',
    content:
      'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
    likes: 4372,
  },
  {
    postId: 'L9W6XD8BO3CZ8YD',
    uid: '0f9ri7vyvezecua6sui',
    timestamp: '09/22/2022',
    name: 'Mata',
    username: 'mtraynorw',
    content: 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',
    likes: 3404,
  },
  {
    postId: '2AA3K3S8M2LHV28',
    uid: 'ol0mim9txg5x04v26hd',
    timestamp: '02/24/2022',
    name: 'Earle',
    username: 'eparfittx',
    content: 'Sed ante. Vivamus tortor. Duis mattis egestas metus.',
    likes: 293,
  },
  {
    postId: '76LAYSZMHCN56OG',
    uid: '5h0cqh4kavzz4x5grky',
    timestamp: '01/18/2022',
    name: 'Lazar',
    username: 'lnevilley',
    content: 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',
    likes: 2006,
  },
  {
    postId: '7RFRZWDM2UFUUDG',
    uid: 'un2di33mmrio5xq2mkq',
    timestamp: '11/23/2022',
    name: 'Vanni',
    username: 'vmuselliz',
    content:
      'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.',
    likes: 145,
  },
  {
    postId: '258SZQZMJOR23MI',
    uid: '5jtusf7r46hhwl5qtky',
    timestamp: '07/18/2022',
    name: 'Holt',
    username: 'hmounsie10',
    content:
      'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',
    likes: 7491,
  },
  {
    postId: 'JYC3YFRNV15184Z',
    uid: 'r2snyhc9rjc9frl5yg2',
    timestamp: '07/12/2022',
    name: 'Martyn',
    username: 'mfarrington11',
    content:
      'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
    likes: 8796,
  },
  {
    postId: 'ALE4ENB9D8P3LGZ',
    uid: 'wql6dkxjtt7q24zpme5',
    timestamp: '03/03/2022',
    name: 'Edvard',
    username: 'eomailey12',
    content:
      'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
    likes: 6012,
  },
  {
    postId: 'IEB1DK9YCQ34WH2',
    uid: '7q2gs8btnktqouxmf34',
    timestamp: '11/09/2022',
    name: 'Noami',
    username: 'nlanchester13',
    content: 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
    likes: 5157,
  },
  {
    postId: '9NMFDYBG3XIPE1B',
    uid: 'ltxrqbjhb0awrblkogm',
    timestamp: '10/29/2022',
    name: 'Lora',
    username: 'llebatteur14',
    content:
      'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',
    likes: 2788,
  },
  {
    postId: 'UVV8U74U1LT0KY8',
    uid: '06a1wk9k9iqvy5js22z',
    timestamp: '05/18/2022',
    name: 'Verine',
    username: 'vairton15',
    content: 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.',
    likes: 3988,
  },
  {
    postId: '5XXDS3D6VJ2I7KW',
    uid: 'q9twmau3jgx84b7w6x5',
    timestamp: '02/10/2022',
    name: 'Keslie',
    username: 'kmacparlan16',
    content:
      'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',
    likes: 6037,
  },
  {
    postId: '63F0CGFUWRIB14D',
    uid: 'miygxqaflb2oyczdv5r',
    timestamp: '02/27/2022',
    name: 'Frederich',
    username: 'fsamms17',
    content:
      'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.',
    likes: 9631,
  },
  {
    postId: 'PFBVUIN9M4DWY32',
    uid: 'jvh4tlliddsgnfkr3mu',
    timestamp: '08/30/2022',
    name: 'Valaree',
    username: 'vegiloff18',
    content:
      'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
    likes: 4474,
  },
  {
    postId: 'PS9B176PMVTZBOT',
    uid: 'z3m7ye6dqmxs3mjzilx',
    timestamp: '10/29/2022',
    name: 'Eudora',
    username: 'ejacquet19',
    content:
      'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.',
    likes: 5671,
  },
  {
    postId: 'SQCJS1JQJZLILZ6',
    uid: 'owu1vxcbrb7ruo6wszy',
    timestamp: '01/28/2022',
    name: 'Justin',
    username: 'jgillino1a',
    content:
      'Phasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
    likes: 1939,
  },
  {
    postId: 'BM62QDLG263O7MX',
    uid: 'oh7px2w9mz7c87ei0su',
    timestamp: '11/26/2022',
    name: 'Debor',
    username: 'ddamato1b',
    content:
      'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',
    likes: 8844,
  },
  {
    postId: '6UX9EXBLMMBVBV6',
    uid: '7l1k5wr46gcljry30w8',
    timestamp: '01/21/2022',
    name: 'Shawna',
    username: 'sstrete1c',
    content:
      'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',
    likes: 6873,
  },
  {
    postId: 'A5F9GSBO75IEXR3',
    uid: 'f1yjsbsqojywns0fwdv',
    timestamp: '09/21/2022',
    name: 'Addy',
    username: 'alongfellow1d',
    content:
      'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',
    likes: 6816,
  },
]
